// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANWTb0XMHUUbxqKPDkTw-kmc_p-wmSYBE',
    appId: '1:752207806635:web:434c96cc52dfed8b69b7ee',
    messagingSenderId: '752207806635',
    projectId: 'marwadiparking',
    authDomain: 'marwadiparking.firebaseapp.com',
    databaseURL: 'https://marwadiparking-default-rtdb.firebaseio.com',
    storageBucket: 'marwadiparking.firebasestorage.app',
    measurementId: 'G-97ZNVCSTLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPfoDd3wSJI4bF-4IjOqKw4a9vPwHItrI',
    appId: '1:752207806635:android:6f41b5f0a08b76db69b7ee',
    messagingSenderId: '752207806635',
    projectId: 'marwadiparking',
    databaseURL: 'https://marwadiparking-default-rtdb.firebaseio.com',
    storageBucket: 'marwadiparking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYz2CJe4amGaxUkAusgvGqnuhLYfPmf0c',
    appId: '1:752207806635:ios:ea809728f0c2a73969b7ee',
    messagingSenderId: '752207806635',
    projectId: 'marwadiparking',
    databaseURL: 'https://marwadiparking-default-rtdb.firebaseio.com',
    storageBucket: 'marwadiparking.firebasestorage.app',
    iosBundleId: 'com.example.marwadiParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYz2CJe4amGaxUkAusgvGqnuhLYfPmf0c',
    appId: '1:752207806635:ios:ea809728f0c2a73969b7ee',
    messagingSenderId: '752207806635',
    projectId: 'marwadiparking',
    databaseURL: 'https://marwadiparking-default-rtdb.firebaseio.com',
    storageBucket: 'marwadiparking.firebasestorage.app',
    iosBundleId: 'com.example.marwadiParking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANWTb0XMHUUbxqKPDkTw-kmc_p-wmSYBE',
    appId: '1:752207806635:web:30aa6d1e994dcc9f69b7ee',
    messagingSenderId: '752207806635',
    projectId: 'marwadiparking',
    authDomain: 'marwadiparking.firebaseapp.com',
    databaseURL: 'https://marwadiparking-default-rtdb.firebaseio.com',
    storageBucket: 'marwadiparking.firebasestorage.app',
    measurementId: 'G-PZP5F38SP9',
  );
}
